"""add hls storage keys

Revision ID: 0be27618d4cf
Revises: e383c25fa183
Create Date: 2026-07-24 17:35:40.681976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be27618d4cf'
down_revision: Union[str, Sequence[str], None] = 'e383c25fa183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('hls_playlist_key', sa.String(length=512), nullable=True))
    op.add_column('tracks', sa.Column('hls_key_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'hls_key_key')
    op.drop_column('tracks', 'hls_playlist_key')
    # ### end Alembic commands ###
