"""add_synced_lyrics

Revision ID: 202262bb2b0e
Revises: 05e8b09d474c
Create Date: 2026-08-02 01:40:22.793053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202262bb2b0e'
down_revision: Union[str, Sequence[str], None] = '05e8b09d474c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_lyric_chunks_embedding'), table_name='lyric_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_recently_played_user_played_at'), table_name='recently_played')
    op.drop_index(op.f('idx_recently_played_user_track'), table_name='recently_played')
    op.alter_column('refresh_token', 'token_hash',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('tracks', sa.Column('synced_lyrics', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('word_timestamps', sa.JSON(), nullable=True))
    op.add_column('tracks', sa.Column('lyrics_offset_ms', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_tracks_embedding'), table_name='tracks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_tracks_lyrics_tsv'), table_name='tracks', postgresql_using='gin')
    op.drop_index(op.f('idx_tracks_search_tsv'), table_name='tracks', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tracks_search_tsv'), 'tracks', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_tracks_lyrics_tsv'), 'tracks', ['lyrics_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_tracks_embedding'), 'tracks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('tracks', 'lyrics_offset_ms')
    op.drop_column('tracks', 'word_timestamps')
    op.drop_column('tracks', 'synced_lyrics')
    op.alter_column('refresh_token', 'token_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.create_index(op.f('idx_recently_played_user_track'), 'recently_played', ['user_id', 'track_id'], unique=False)
    op.create_index(op.f('idx_recently_played_user_played_at'), 'recently_played', ['user_id', sa.literal_column('played_at DESC')], unique=False)
    op.create_index(op.f('idx_lyric_chunks_embedding'), 'lyric_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
