"""add_guitar_piano_stem_keys_to_drafts

Revision ID: 317c2e9d0700
Revises: 202262bb2b0e
Create Date: 2026-08-03 11:24:54.571971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '317c2e9d0700'
down_revision: Union[str, Sequence[str], None] = '202262bb2b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('split_guitar_key', sa.String(length=512), nullable=True))
    op.add_column('drafts', sa.Column('split_piano_key', sa.String(length=512), nullable=True))
    op.drop_index(op.f('idx_lyric_chunks_embedding'), table_name='lyric_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_recently_played_user_played_at'), table_name='recently_played')
    op.drop_index(op.f('idx_recently_played_user_track'), table_name='recently_played')
    op.alter_column('refresh_token', 'token_hash',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('track_artists_artist_id_fkey'), 'track_artists', type_='foreignkey')
    op.create_foreign_key(None, 'track_artists', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_tracks_embedding'), table_name='tracks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_tracks_lyrics_tsv'), table_name='tracks', postgresql_using='gin')
    op.drop_index(op.f('idx_tracks_search_tsv'), table_name='tracks', postgresql_using='gin')
    op.drop_column('tracks', 'lyrics_offset_ms')
    op.drop_column('tracks', 'synced_lyrics')
    op.drop_column('tracks', 'word_timestamps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('word_timestamps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('synced_lyrics', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('lyrics_offset_ms', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_tracks_search_tsv'), 'tracks', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_tracks_lyrics_tsv'), 'tracks', ['lyrics_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_tracks_embedding'), 'tracks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'track_artists', type_='foreignkey')
    op.create_foreign_key(op.f('track_artists_artist_id_fkey'), 'track_artists', 'users', ['artist_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_token', 'token_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.create_index(op.f('idx_recently_played_user_track'), 'recently_played', ['user_id', 'track_id'], unique=False)
    op.create_index(op.f('idx_recently_played_user_played_at'), 'recently_played', ['user_id', sa.literal_column('played_at DESC')], unique=False)
    op.create_index(op.f('idx_lyric_chunks_embedding'), 'lyric_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('drafts', 'split_piano_key')
    op.drop_column('drafts', 'split_guitar_key')
    # ### end Alembic commands ###
