"""add_verification_and_access_tokens

Revision ID: 7e4cd677b434
Revises: 0be27618d4cf
Create Date: 2026-07-25 11:47:11.304231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4cd677b434'
down_revision: Union[str, Sequence[str], None] = '0be27618d4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('user_otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('otp_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('refresh_token', sa.Column('family_id', sa.String(length=255), nullable=True))
    op.execute("UPDATE refresh_token SET family_id = 'legacy'")
    op.alter_column('refresh_token', 'family_id', nullable=False)
    op.add_column('refresh_token', sa.Column('used_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'refresh_token', ['token_hash'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    op.drop_column('refresh_token', 'used_at')
    op.drop_column('refresh_token', 'family_id')
    op.drop_table('user_otp')
    op.drop_table('access_token')
    # ### end Alembic commands ###
